image: archlinux/base

stages:
    - test
    - deploy

testbench(py3):
    stage: test
    before_script:
        - pacman -Syu --noconfirm python-numpy python-pip
    script:
        - python ./test.py -vv

doctest:
    stage: test
    before_script:
        - pacman -Syu --noconfirm python-numpy python-pip
        - pip install sphinx sphinx_rtd_theme numpydoc
    script:
        - sphinx-build -b doctest docs doctest

# Pypi done manually. 
# pypi:
#     stage: deploy
#     before_script:
#         - pacman -Syu --noconfirm git twine python-numpy
#     variables:
#         USERNAME: $PYPI_USERNAME
#         PASSWORD: $PYPI_PASSWORD
#     script:
#         - python setup.py sdist
#         - twine upload --skip-existing dist/*
#     only:
#         - master
#         - pypi

pages:
    stage: deploy
    before_script:
        - pacman -Syu --noconfirm python-numpy python-pip
        - pip install sphinx sphinx_rtd_theme numpydoc
    script:
        - sphinx-build -b html docs html
        - mkdir public
        - mv html/* public
    artifacts:
        paths:
            - public
    only:
        - master
        - doc
